### ISSUE TITLE
Plugin stopped working after I updated my chrome

### ISSUE THREAD

**Issue by someone-random1** [scholtzm/steam-trade-offer-enhancer#10]
Idk why but my chrome updated by its own and now the plugin doesn't work
![image](https://user-images.githubusercontent.com/66572183/200147493-e2c69633-958c-49b1-88c1-acbadb9c49cb.png)

Chrome version: 107.0.5304.88
64 bits

**Comment by scholtzm** [comment]
Works for me in **Chrome Version 107.0.5304.88 (Official Build) (64-bit)** and also latest Firefox.

Is it possible the script is either not installed or clashing with other script/extension?
